spring:
  application:
    name: person-front
  thymeleaf:
    cache: false


server:
  port: 8080

logging:
  config: classpath:log-config.xml

# This is a configuration defined to setup the RestTemplate
rest:
  consul:
    root:
      uri: "http://localhost:8081"
