spring:
  application:
    name: person-service-client
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:file:~/consul-example;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
      path: /console

# To use gorm you need this configuration at this level
hibernate:
  hbm2ddl:
    auto: update

server:
  port: 8081

logging:
  config: classpath:log-config.xml

